// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPBCeEDTuWsMXjI_5aXEKUuddC8DWVuQI',
    appId: '1:974635157908:web:dca3a8d9987fd7f072a781',
    messagingSenderId: '974635157908',
    projectId: 'elearning-flutter-app',
    authDomain: 'elearning-flutter-app.firebaseapp.com',
    storageBucket: 'elearning-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtYaitMX_AxThDR75fW8dmoDbeFMH4Fz8',
    appId: '1:974635157908:android:7da701e051d0c3cd72a781',
    messagingSenderId: '974635157908',
    projectId: 'elearning-flutter-app',
    storageBucket: 'elearning-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Lo7Wn_4kESs7PaRwXl02Y0d5WZBl0UI',
    appId: '1:974635157908:ios:89d787ce276e129c72a781',
    messagingSenderId: '974635157908',
    projectId: 'elearning-flutter-app',
    storageBucket: 'elearning-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.elearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Lo7Wn_4kESs7PaRwXl02Y0d5WZBl0UI',
    appId: '1:974635157908:ios:89d787ce276e129c72a781',
    messagingSenderId: '974635157908',
    projectId: 'elearning-flutter-app',
    storageBucket: 'elearning-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.elearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPBCeEDTuWsMXjI_5aXEKUuddC8DWVuQI',
    appId: '1:974635157908:web:e37817833afde9e472a781',
    messagingSenderId: '974635157908',
    projectId: 'elearning-flutter-app',
    authDomain: 'elearning-flutter-app.firebaseapp.com',
    storageBucket: 'elearning-flutter-app.firebasestorage.app',
  );
}
